name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v2

      # Set up Bun with the latest version
      - name: Set up Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          version: latest

      # Set up Bun with a specific version and cache
      - name: Set up Bun (specific version with cache)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1
          cache: "bun"

      # Install dependencies with Bun
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Run lint and build commands with Bun
      - name: Run lint and build
        run: bun run build:prepare
