name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bun/action-setup-bun@v1
        with:
          version: latest
      - uses: actions/setup-bun@v1
        with:
          bun-version: 1.1.1
          cache: "bun"
      - run: bun install --frozen-lockfile
      - name: Create Release Pull Request and Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run build && bun run release
