name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Set up Node (lts)
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.0.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Run lint and build
        run: pnpm run build:prepare
