name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          no-cache: false

      - name: Install dependencies
        run: bun i

      - name: Run lint and build
        run: bun run build:prepare
