name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
     # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v2

      # Set up Bun with the latest version
      - name: Set up Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          no-cache: false

      # Install dependencies with Bun
      - name: Install dependencies
        run: bun install

      # Run lint and build commands with Bun
      - name: Run lint and build
        run: bun run build:prepare

      # Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --tag latest
