name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Set up Bun with the latest version
      - name: Set up Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          no-cache: false

      # Install dependencies with Bun
      - name: Install dependencies
        run: bun install

      - name: Create release pull request and publish to npm
        id: changeset
        uses: changesets/action@v1
        with:
          publish: bun changeset publish
          commit: 'chore: release'
          title: 'chore: release'
        env:
          ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}