name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v2

      # Set up Bun with the latest version
      - name: Set up Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          no-cache: false

      # Install dependencies with Bun
      - name: Install dependencies
        run: bun install

      - name: Create GitHub release and publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun install --global @changesets/cli
          bunx changeset version
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ci(changesets): version packages"
          git push
          bunx changeset publish

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.ref }}
          release_name: Release ${{ github.event.ref }}
          body: |
            This release includes the following changes:
            ${{ steps.changeset.outputs.content }}
          draft: false
          prerelease: false
